### ISSUE TITLE
Compute Inverse of the matrix 

### ISSUE THREAD

**Issue by Pana1v** [Coding-Club-IITG/Git-Workshop-Cpp#18]
Add the functionality to compute the adjoint of a matrix, thereby using that to compute the inverse!

**Comment by Pana1v** [comment]
I'd like to work on this issue!

**Comment by nandita27iitp** [comment]
Please assign this issue to me! 😇

**Comment by darishkhan155** [comment]
I can do this well. Can I get it assigned to me?

**Comment by re4lvanshsingh** [comment]
could you assign me this? Will complete it in a breeze since I have already contributed to this project

**Comment by LAKSHYA25102003** [comment]
pls assign this issue to me.
