### ISSUE TITLE
Solve A System Of Equations In 3 Variable Using Matrices

### ISSUE THREAD

**Issue by kirtan05** [Coding-Club-IITG/Git-Workshop-Cpp#19]
This is an important part in Linear Algebra

**Comment by kirtan05** [comment]
Claim
Can I solve this issue too ?

**Comment by nandita27iitp** [comment]
Please assign this issue to me!

**Comment by ayushs404** [comment]
I want to work on this issue. Please assign me.

**Comment by haripriya120603** [comment]
I want to work on this issue

**Comment by haripriya120603** [comment]
Assign it to me

**Comment by Sparsh752** [comment]
Please assign this work to me

**Comment by haripriya120603** [comment]
Assign this to me

**Comment by Ayushiitp** [comment]
please assign this issue to me

**Comment by LAKSHYA25102003** [comment]
please assign this issue to me
